{
 "title": "MSK",
 "description": "Dashboard for metrics jmx_exporter protmetheus",
 "tags": [
  "aws",
  "kafka"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kafka_controller_ControllerStats_Count{job=\"msk\"},cluster_name)"
    }
   },
   {
    "name": "broker",
    "label": "Broker",
    "query": {
     "query": "label_values(kafka_controller_KafkaController_Value{cluster_name=\"$cluster\", job=\"msk\"},instance)"
    }
   },
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(kafka_consumer_group_ConsumerLagMetrics_Value{cluster_name=~\"$cluster\", job=\"msk\"},groupId)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_cluster_Partition_Value{cluster_name=~\"$cluster\", job=\"msk\"},topic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(cluster_name) (kafka_server_ReplicaManager_Value{name=\"LeaderCount\", cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster_name)(kafka_controller_KafkaController_Value{job=\"msk\", name=\"ActiveControllerCount\", cluster_name=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total of Topics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster_name) (kafka_controller_KafkaController_Value{job=\"msk\", name=\"GlobalTopicCount\",cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster_name) (kafka_server_ReplicaManager_Value{name=\"UnderReplicatedPartitions\", job=\"msk\", cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster_name) (kafka_server_ReplicaManager_Value{name=\"PartitionCount\", job=\"msk\", cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster_name) (kafka_server_ReplicaManager_Value{name=\"OfflineReplicaCount\", job=\"msk\", cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Controller and Followers ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_Value{name=\"ActiveControllerCount\", job=\"msk\", cluster_name=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Replica Per Broker",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "count by(instance) (kafka_cluster_Partition_Value{name=\"ReplicasCount\", job=\"msk\", cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Network Processor Avg Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "repeat": "broker",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kafka_network_SocketServer_Value{name=\"NetworkProcessorAvgIdlePercent\", job=\"msk\",instance=~\"$broker\", cluster_name=~\"$cluster\"} * 100)"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(request) (quantile(0.99, kafka_network_RequestMetrics_Count{name=\"TotalTimeMs\", request=\"Produce\", job=\"msk\", instance=~\"$broker\", cluster_name=~\"$cluster\"}))",
     "legendFormat": "Total Time"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(request) (quantile(0.99, kafka_network_RequestMetrics_Count{name=\"TotalTimeMs\", request=\"FetchConsumer\", job=\"msk\", instance=~\"$broker\", cluster_name=~\"$cluster\"}))",
     "legendFormat": "Total Time"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(request) (quantile(0.99, kafka_network_RequestMetrics_Count{name=\"TotalTimeMs\", request=\"FetchFollower\", job=\"msk\", instance=~\"$broker\", cluster_name=~\"$cluster\"}))",
     "legendFormat": "Total Time"
    }
   ]
  },
  {
   "title": "Produce Latency 99th per Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(request) (quantile(0.99, kafka_network_RequestMetrics_Count{name=\"TotalTimeMs\", request=\"Produce\", job=\"msk\", instance=~\"$broker\", cluster_name=~\"$cluster\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "FetchConsumer Latency 99th per Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(request) (quantile(0.99, kafka_network_RequestMetrics_Count{name=\"TotalTimeMs\", request=\"FetchConsumer\", job=\"msk\", instance=~\"$broker\", cluster_name=~\"$cluster\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "FetchFollow Latency 99th per Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(request) (quantile(0.99, kafka_network_RequestMetrics_Count{name=\"TotalTimeMs\", request=\"FetchFollower\", job=\"msk\", instance=~\"$broker\", cluster_name=~\"$cluster\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Messages In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sort(sum by(topic) (irate(kafka_server_BrokerTopicMetrics_Count{name=~\"MessagesInPerSec\", job=\"msk\", topic=~\"$topic\", instance=~\"$broker\", cluster_name=~\"$cluster\"}[5m])))",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort(sum by(topic) (irate(kafka_server_BrokerTopicMetrics_Count{name=~\"BytesInPerSec\", job=\"msk\", topic=~\"$topic\", instance=~\"$broker\", cluster_name=~\"$cluster\"}[5m])))",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Produce Request Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sort(sum by(instance) (irate(kafka_network_RequestMetrics_Count{request=~\"Produce\", job=\"msk\", instance=~\"$broker\", cluster_name=~\"$cluster\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Produce Request Rate Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(topic) (irate(kafka_server_BrokerTopicMetrics_Count{name=~\"TotalProduceRequestsPerSec\", job=\"msk\", topic=~\"$topic\", instance=~\"$broker\", cluster_name=~\"$cluster\"}[5m]))",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort(sum by(topic) (irate(kafka_server_BrokerTopicMetrics_Count{name=~\"BytesOutPerSec\", job=\"msk\", topic=~\"$topic\", instance=~\"$broker\", cluster_name=~\"$cluster\"}[5m])))",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In / Out Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(kafka_server_BrokerTopicMetrics_Count{name=~\"BytesOutPerSec\", job=\"msk\", topic=~\"$topic\", instance=~\"$broker\", cluster_name=~\"$cluster\"}[5m]))",
     "legendFormat": "Bytes Out [{{instance}}]"
    },
    {
     "expr": "sum by(instance) (irate(kafka_server_BrokerTopicMetrics_Count{name=~\"BytesInPerSec\", job=~\"$job\", topic=~\"$topic\", instance=~\"$broker\", cluster_name=~\"$cluster\"}[5m]))",
     "legendFormat": "Bytes In [{{instance}}]"
    }
   ]
  },
  { "title": "Consumer Lags", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Sum Offset Lag",
   "type": "stat",
   "description": "above 0",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(groupId) (kafka_consumer_group_ConsumerLagMetrics_Value{name=\"SumOffsetLag\", job=\"msk\", groupId=~\"$group\", cluster_name=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum Offset Lag by Group&Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "sum by(groupId, topic) (kafka_consumer_group_ConsumerLagMetrics_Value{name=\"SumOffsetLag\",job=\"msk\",groupId=~\"$group\",topic=~\"$topic\", cluster_name=~\"$cluster\"})",
     "legendFormat": "Group: {{groupId}}, Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Top 5 Partitions by Offset Lag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, kafka_consumer_group_ConsumerLagMetrics_Value{name=\"OffsetLag\", job=\"msk\", groupId=~\"$group\", topic=~\"$topic\", cluster_name=~\"$cluster\"})",
     "legendFormat": "Group: {{groupId}}, Topic: {{topic}}, Partition: {{partition}}"
    }
   ]
  },
  {
   "title": "Partitions Offset Lag Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "kafka_consumer_group_ConsumerLagMetrics_Value{name=\"OffsetLag\", job=\"msk\", groupId=~\"$group\", topic=~\"$topic\", cluster_name=~\"$cluster\"} > 0",
     "legendFormat": "Group: {{groupId}}, Topic: {{topic}}, Partition: {{partition}}"
    }
   ]
  },
  {
   "title": "Top 5 Topics by Estimated Time Lag",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, max by(topic) (kafka_consumer_group_ConsumerLagMetrics_Value{name=\"EstimatedTimeLag\", job=\"msk\", groupId=~\"$group\", topic=~\"$topic\", cluster_name=~\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum Estimated Time Lag Per Group&Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_consumer_group_ConsumerLagMetrics_Value{name=\"EstimatedMaxTimeLag\", job=\"msk\", cluster_name=~\"$cluster\", groupId=~\"$group\", topic=~\"$topic\"}",
     "legendFormat": "Group: {{groupId}}, Topic: {{topic}}"
    }
   ]
  },
  { "title": "Troubleshooting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Failed Produce Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_Count{name=~\"FailedFetchRequestsPerSec\", job=\"msk\", cluster_name=~\"$cluster\", instance=~\"$broker\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Fetch Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_Count{name=~\"FailedProduceRequestsPerSec\", job=\"msk\", cluster_name=~\"$cluster\", instance=~\"$broker\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Disconnects Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(kafka_server_SessionExpireListener_Count{job=\"msk\", cluster_name=~\"$cluster\", name=~\"ZooKeeperDisconnectsPerSec\", instance=~\"$broker\"}[1m])",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Expires Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(kafka_server_SessionExpireListener_Count{job=\"msk\", cluster_name=~\"$cluster\", name=~\"ZooKeeperExpiresPerSec\", instance=~\"$broker\"}[1m])",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Request Latency Ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_server_ZooKeeperClientMetrics_Count{job=\"msk\", cluster_name=~\"$cluster\", name=~\"ZooKeeperRequestLatencyMs\", instance=~\"$broker\"}",
     "legendFormat": "Broker: {{instance}}"
    }
   ]
  },
  {
   "title": "ISR Shrinks / Expands Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(kafka_server_ReplicaManager_Count{job=\"msk\", cluster_name=~\"$cluster\", name=~\"IsrShrinksPerSec\", instance=~\"$broker\"}[1m])",
     "legendFormat": "ISR Shrinks Per Sec"
    },
    {
     "expr": "irate(kafka_server_ReplicaManager_Count{job=\"msk\", cluster_name=~\"$cluster\", name=~\"IsrExpandsPerSec\", instance=~\"$broker\"}[1m])",
     "legendFormat": "ISR Expands Per Sec"
    }
   ]
  },
  {
   "title": "Total Fetch Request Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(kafka_server_BrokerTopicMetrics_Count{job=\"msk\", cluster_name=~\"$cluster\", name=~\"TotalFetchRequestsPerSec\", instance=~\"$broker\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "FetchConsumer Request Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(kafka_network_RequestMetrics_Count{request=~\"FetchConsumer\", job=\"msk\", cluster_name=~\"$cluster\",instance=~\"$broker\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "FetchFollower Request Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(kafka_network_RequestMetrics_Count{request=~\"FetchFollower\", job=\"msk\", cluster_name=~\"$cluster\", instance=~\"$broker\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Requests Waiting in the Producer Purgatory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_DelayedOperationPurgatory_Value{job=\"msk\", cluster_name=~\"$cluster\", name=~\"NumDelayedOperations\", delayedOperation=~\"Produce\", instance=~\"$broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Requests Waiting in the Fetch Purgatory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_server_DelayedOperationPurgatory_Value{delayedOperation=~\"Fetch\", job=\"msk\", cluster_name=~\"$cluster\", instance=~\"$broker\"})",
     "legendFormat": "Broker {{instance}}"
    }
   ]
  },
  {
   "title": "Log Flush Stats Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(kafka_log_LogFlushStats_Count{name=\"LogFlushRateAndTimeMs\", job=\"msk\", cluster_name=~\"$cluster\",instance=~\"$broker\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Leader Election Rate Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(kafka_controller_ControllerStats_Count{name=\"LeaderElectionRateAndTimeMs\", job=\"msk\", cluster_name=~\"$cluster\", instance=~\"$broker\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Java Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 } },
  {
   "title": "Java Memory Usage (Verbose)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "java_lang_Memory_Verbose{job=\"msk\", cluster_name=~\"$cluster\", instance=~\"$broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(java_lang_Memory_HeapMemoryUsage_used{job=\"msk\", cluster_name=~\"$cluster\",instance=~\"$broker\"} )",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  }
 ]
}